language: python
python: "3.6.4"
before_install:
  - mv ./travis_secrets.yaml ./secrets.yaml
  - rm -y ./packages/stream.yaml
install:
  - pip3 install homeassistant
  - pip3 install colorlog
script:
  - hass -c ./ --script check_config --info all
