language: python

python: "3.6.4"

before_install:
  - touch fake_key.pem
  - mv ./travis_secrets.yaml ./secrets.yaml

install: pip3 install homeassistant

script: hass -c config/ --script check_config --info all