---
sequence:
  - service: script.notify_web
    data:
      type: warning
      message: "Config ‚úîÔ∏è begins."
      duration: 15

  # Run the config_check
  - service: config_check.run

  # Wait for the notification to appear
  - wait_template: "{{ states('persistent_notification.1337') is string }}"
    timeout: 00:03:00

  - alias: 'Dismiss the persistent notification if the check went well.'
    choose:
      - conditions: '{{ state_attr("persistent_notification.1337", "message")|trim == "Configuration is OK!" }}'
        sequence:
          - service: persistent_notification.dismiss
            data:
              notification_id: "1337"

          - service: script.notify_web
            data:
              type: success
              message: "Config ‚úîÔ∏è = üëç"
              duration: 15

    default:
      - variables:
          message: |
            {% set message = state_attr('persistent_notification.1337','message') | trim %}
            {% set message = message | replace("config/integrations/homeassistant/../../", "") %}
            {% set message = message | replace("[1m", "") | replace("[1;37m", "") | replace("[1;31m", "") %}
            {% set message = message | replace(":", ": ") %}
            {{ message | trim }}

      - service: script.notify_web
        data:
          type: alert
          title: Config check error
          message: "{{ message }}"

      - service: script.turn_off
        target:
          entity_id:
            - script.automation_reload
            - script.config_check_and_reboot_server
            - script.check_and_restart
            - script.script_reload
