platform: rest
name: Docker UniFi
resource: http://10.0.0.4:8126/container/unifi-controller
body_on: '{"state": "start"}'
body_off: '{"state": "stop"}'
is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
